WeightScale.WorkstationsChecker/WeightScale.WorkstationsChecker.Web/Areas/PowerUser/Controllers/ObserverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using WeightScale.WorkstationsChecker.Data;
using WeightScale.WorkstationsChecker.Model;
using WeightScale.WorkstationsChecker.Web.Models;

namespace WeightScale.WorkstationsChecker.Web.Areas.PowerUser.Controllers
{
    public class ObserverController : PowerUserController
    {
        private readonly IUowData context;
        public ObserverController(IUowData contextParam)
        {
            this.context = contextParam;
        }

        // GET: PowerUser/Observer
        public ActionResult Index()
        {
            var observedWorkstations = this.context.WeightScales.All();
            return View(Mapper.Map<IEnumerable<WorkstationViewModel>>(observedWorkstations));
        }

        // GET: PowerUser/Observer/Edit
        public ActionResult Edit(int id)
        {
            var workstation = context.WeightScales.All().FirstOrDefault(x => x.Id == id);
            ViewBag.Title = string.Format("Edit workstation {0}", workstation.Name);

            return View(Mapper.Map<WorkstationViewModel>(workstation));
        }

        // GET: PowerUser/Observer/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WorkstationViewModel workstation)
        {
            if (ModelState.IsValid)
            {
                var dbWorkStation = context.WeightScales.GetById(workstation.Id);
                Mapper.Map(workstation, dbWorkStation);
                context.WeightScales.Update(dbWorkStation);
                context.SaveChanges();
            }
            else
            {
                return View(workstation);
            }

            return RedirectToAction("Index");
        }

        // GET: PowerUser/Observer/Edit
        public ActionResult Create()
        {
            ViewBag.Title = string.Format("Create new workstation observer");
            return View("Edit");
        }

        // GET: PowerUser/Observer/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WorkstationViewModel workstation)
        {
            if (ModelState.IsValid)
            {
                var dbWorkStation = Mapper.Map<WeightScaleWorkStation>(workstation);
                context.WeightScales.Add(dbWorkStation);
                context.SaveChanges();
            }
            else
            {
                ViewBag.Title = string.Format("Create new workstation observer");
                return View("Edit", (object)workstation);
            }

            return RedirectToAction("Index");
        }

        // GET: PowerUser/Observer/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            context.WeightScales.Delete(id);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WeightScale.WorkstationsChecker/WeightScale.WorkstationsChecker.Web/Areas/PowerUser/Views/Observer/Edit.cshtml
@model WeightScale.WorkstationsChecker.Web.Models.WorkstationViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">@ViewBag.Title</div>
        <div class="panel-body">
            @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                if (@Model != null && @Model.Id != 0)
                {
                    <div class="form-group">
                        @Html.LabelFor(m => m.Id, new { @class = "control-label" })
                        @Html.EditorFor(m => m.Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(m => m.Id, string.Empty, new { @class = "text-danger" })
                    </div>
                }

                <div class="form-group">
                    @Html.LabelFor(m => m.Address, new { @class = "control-label" })
                    @Html.EditorFor(m => m.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(m => m.Address, string.Empty, new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Name, new { @class = "control-label" })
                    @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(m => m.Name, string.Empty, new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.ScreenPosition, new { @class = "control-label" })
                    @Html.EditorFor(m => m.ScreenPosition, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(m => m.ScreenPosition, string.Empty, new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.IsStopped, new { @class = "control-label" })
                    @Html.EditorFor(m => m.IsStopped)
                    @Html.ValidationMessageFor(m => m.IsStopped, string.Empty, new { @class = "text-danger" })
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
                @Html.ActionLink("Cancel", "Index", "Observer", new { area = "PowerUser" }, new { @class = "btn btn-default" })
            }
        </div>
    </div>
</div>

WeightScale.WorkstationsChecker/WeightScale.WorkstationsChecker.Web/Areas/PowerUser/Views/Observer/Index.cshtml
@using WeightScale.WorkstationsChecker.Web.Models;

@model IEnumerable<WorkstationViewModel>
@{
    ViewBag.Title = "Observed workstations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">@ViewBag.Title</div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>@Html.LabelFor(m => m.First().Id)</th>
                    <th>@Html.LabelFor(m => m.First().Address)</th>
                    <th>@Html.LabelFor(m => m.First().Name)</th>
                    <th>@Html.LabelFor(m => m.First().ScreenPosition)</th>
                    <th>@Html.LabelFor(m => m.First().IsStopped)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() == 0)
                {
                    <tr><td colspan="4" class="text-center">There is no observed workstations</td></tr>
                }
                else
                {
                    foreach (var workstation in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(m => workstation.Id)</td>
                            <td>@Html.DisplayFor(m => workstation.Address)</td>
                            <td>@Html.DisplayFor(m => workstation.Name)</td>
                            <td>@Html.DisplayFor(m => workstation.ScreenPosition)</td>
                            <td>@Html.DisplayFor(m => workstation.IsStopped)</td>
                            <td>
                                @using (Html.BeginForm("Delete", "Observer", new { id = workstation.Id }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ActionLink("Edit", "Edit",
                                        new { id = workstation.Id, area = "PowerUser" },
                                        new { @class = "btn btn-primary btn-xs" })
                                    <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                                }
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary" })
</div>